CREATE DATABASE WishList;

USE WishList;

CREATE TABLE Desejos
(
	idDesejo INT PRIMARY KEY IDENTITY
	,Descricao VARCHAR(150) NOT NULL
	,DataCriacao DATE NOT NULL
	,idUsuario INT FOREIGN KEY REFERENCES Usuarios(idUsuario)
);

CREATE TABLE Usuarios
(
	idUsuario INT PRIMARY KEY IDENTITY
	,email VARCHAR(200) NOT NULL UNIQUE
	,senha VARCHAR(200) NOT NULL

);

SELECT * FROM Usuarios;
SELECT * FROM Desejos;

